### ISSUE TITLE
java native contract runs unstable

### ISSUE THREAD

**Issue by springrain** [xuperchain/xuperchain#1005]
**Brief of the issue**
```./xchain-cli native invoke --method get -a '{"key":"stones"}' javacounter --fee 100 -H 127.0.0.1:37103```
Random return
```PreExe contract response : rpc error: code = Unknown desc = get contract desc for 'javacounter' error:Key not found, logid:1614843174460667909_1_8081```
There is no 1614843174460667909_1_8081 in the log

or

```shell
contract response: 2
The gas you cousume is: 1
The fee you pay is: 100
Tx id: 687e8e6ec357b99f8847019ac0f03f4d9eab9ee3608c13a0035ee5794d3c03af
```

**Your environment**
XuperChain and OS/Go/gcc version etc.

Cluster of 3 servers,cryptotype: "gm", xpoa
xchain-cli version v3.10-9399bae 2021-02-24-09:38:15
CentOS Linux release 7.9.2009 (Core)
go version go1.12.5 linux/amd64
gcc  4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

**Repo steps**
Call the java natvie contract in the example

**Expected behaviours**
Return correct result
```shell
contract response: 2
The gas you cousume is: 1
The fee you pay is: 100
Tx id: 687e8e6ec357b99f8847019ac0f03f4d9eab9ee3608c13a0035ee5794d3c03af
```

**What actually happened**
Random return errors
```PreExe contract response : rpc error: code = Unknown desc = get contract desc for 'javacounter' error:Key not found, logid:1614843174460667909_1_8081```

**Additional information**

**Comment by icexin** [comment]
这个错误的意思是java合约`javacounter`没有部署
