### ISSUE TITLE
xdev编译失败

### ISSUE THREAD

**Issue by monkeycc** [xuperchain/xuperchain#1013]
cd xuperchain
make

------------------------------------

+ go build -o xdev -ldflags '-X main.buildVersion=master -X main.buildDate=2021-03-11-22:31:47 -X main.commitHash=cb4b158' github.com/xuperchain/xuperchain/core/cmd/xdev
-# github.com/xuperchain/xuperchain/core/cmd/xdev/internal/jstest
core/cmd/xdev/internal/jstest/runner.go:165:37: cannot use testDeps{} (type testDeps) as type testing.testDeps in argument to testing.MainStart:
        testDeps does not implement testing.testDeps (missing SetPanicOnExit0 method)
make: *** [Makefile:19：build] 错误 2

---------------------

github.com/xuperchain/xuperchain/core/cmd/xdev

github.com/xuperchain/xuperchain/core/cmd/xdev/internal/jstest

因为这两个网页是404  所以报错？

**Comment by icexin** [comment]
跟 #1024 一样的问题

**Comment by icexin** [comment]
已经在 #1032 里面修复了，感谢关注！
