### ISSUE TITLE
testDeps 缺少 SetPanicOnExit0函数

### ISSUE THREAD

**Issue by littlegirlpppp** [xuperchain/xuperchain#1024]
**Brief of the issue**
Describe here

**Your environment**
XuperChain and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by zsy-cn** [comment]
+ go build -o xdev -gcflags '' -ldflags '-X main.buildVersion=master -X main.buildDate=2021-04-17-13:58:48 -X main.commitHash=3934a9b' github.com/xuperchain/xuperchain/core/cmd/xdev
# github.com/xuperchain/xuperchain/core/cmd/xdev/internal/jstest
core/cmd/xdev/internal/jstest/runner.go:165:37: cannot use testDeps{} (type testDeps) as type testing.testDeps in argument to testing.MainStart:
	testDeps does not implement testing.testDeps (missing SetPanicOnExit0 method)
make: *** [build-release] Error 2

**Comment by icexin** [comment]
已经通过 #1032 解决了，非常感谢！
