### ISSUE TITLE
RESET_INVALID_ERROR found, after clear the table records, and add a record . 

### ISSUE THREAD

**Issue by yueyemingming** [xuperchain/xuperchain#1042]
**Brief of the issue**
RESET_INVALID_ERROR found, after scan del table records, and add a record . 

**Your environment**
OS: ubuntu 16.04
xuperchain : master-2d08ff1 2021-03-09-09:47:21
gcc : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
wasm contract

**Repo steps**
1. make a table, and add some table records
2. del all table records with scan operate. (clear the table records)
3. add a record into the table

**Expected behaviours**
add the record currectly .

**What actually happened**
RESET_INVALID_ERROR occur .

**Additional information**
with the sample code : https://github.com/myxchain/mytable/tree/address

**Comment by icexin** [comment]
这个问题已经复现，初步定位是迭代器对于删除元素验证过程中的bug，非常感谢！

**Comment by chenfengjin** [comment]
问题已[修复](https://github.com/xuperchain/xuperchain/pull/1057)
选择最新的 [3.10 分支](https://github.com/xuperchain/xuperchain/tree/v3.10) 重新构建即可解决
