### ISSUE TITLE
建议p2pv1的时候新增节点，也把节点信息加入到peers列表中。使得./bin/xchain-cli status 可以查到。不用每次都修改network.yaml来实现。

### ISSUE THREAD

**Issue by CodeCmn** [xuperchain/xuperchain#1090]
**Brief of your idea**
建议p2pv1的时候新增节点，也把节点信息加入到peers列表中。使得./bin/xchain-cli status 可以查到。不用每次都修改network.yaml来实现。

**What could be better if XuperChain using your idea**
新增节点是，p2pv1也有节点发现功能，记录添加的节点，并在查看网络状态时，于peers[]显示。

**Are there any side effects?**
Describe what might be worse.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue.

**Comment by uaanaa** [comment]
感谢你的关注和支持，我们后续会进行优化。
