### ISSUE TITLE
Transaction speed?

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1092]
Hello,

Can you please give me an estimation of the Xuperchain TPS for confirmation?

**Comment by chenfengjin** [comment]
xuperchain supports different contract types and contract languages and we are focusing on performance improvement recently.  please wait for detailed performance report for xuperchain v5.x.

As for xuperchain v3.x, we have 4454 2537for

**Comment by chenfengjin** [comment]
xuperchain supports different contract types and contract languages, which  have different TPSs.  What's more performance varies with hardware and softworre(disk,network,cpu,memory,operation system).  

According to a recent benchmark for release v3.10 in our benchmark environment,  TPS for wasm contract is 4454 while  2537 for native contract.
if you wanna find out accurate performance on your machine, you can use xbench [xbench](https://github.com/xuperchain/xbench). 
we only provided usage documentation in Chinese, you can reply in it this thread f you have any question while   using [xbench](https://github.com/xuperchain/xbench))

**Comment by lonnietc** [comment]
Hello,

Thanks for getting back to me on these questions and I have been trying to work my way through the documentation to get a better feel for Xuperchain.

Basically, the goal is to start with a solid ultra-high performant blockchain to build a cryptocurrency platform that may be used as the basis for large number of daily transactions.

I have been looking at a number of C/C++ and Golang blockchains which on the C/C++ side range from NANO (aka Rai Blocks) which uses a Block Lattice approach to make it extremely fast, and FuturePia (on Github) which is supposed to clock in at about 300,000 TPS verified to also QLC Chain (which is an evolved NONO ported to Golang with more features)  to other standard blockchain solutions.

From what I can see of Xuperchain, it seems to have a HUGE number of capabilities and a lot of potential, but may offer way more than I need for the new blockchain project although it does seem to be a good project.

Maybe we could discuss it more on Slack or you can contact me at: Lonnie@outstep.com to see what we might be able to do together and if Xuprtchain is the best solution for my needs.

Looking forward to hearing from you and have a great day,

**Comment by lonnietc** [comment]
Regarding the TPS, I read in your documentation that Xuperchain can have up to 90,000 TPS. How was this verified?

One more question as well.  Does Xuperchain set up PoW consensus for minable cryptocurrency or is it more of dPoS like NANO that is not typically minded, or is it a combination like QLC Chain that has both capabilities at the same time?

**Comment by chenfengjin** [comment]
> Regarding the TPS, I read in your documentation that Xuperchain can have up to 90,000 TPS. How was this verified?
> 
> One more question as well. Does Xuperchain set up PoW consensus for minable cryptocurrency or is it more of dPoS like NANO that is not typically minded, or is it a combination like QLC Chain that has both capabilities at the same time?

90000 TPS(accurate 87000 ) is a benchmark result  and has not been verified in production.
we did this benchmark to explore the upper performance limit of XuperChain core technique(XMODEL,UTXO module etc.).  it is close to our performance design goal.  you can find more information about xuperchain  [here](https://ieeexplore.ieee.org/abstract/document/9192015/).
however it has not bean verified in production as no one of our customers has  business at that scale. 

XuperChain is not designed as a minable cryptocurrency system. Most of our customers use XPOS(an  improved version of DPOS) or XPOA(an improved version of POA)  consensus in their production environment.

You may be interested in [XuperCore](https://github.com/xuperchain/xupercore), A blockchain  framework that allow you to customize  consensus, transaction process etc. according to your need.

**Comment by lonnietc** [comment]
Thanks for explaining on the consensus possibilities, but I a bit confused about the differences between XuperChain and XuperCore.

I have been able to compile and setup the 3-node private cluster for XuperChain, but do not see how it is really different than XuperCore which I have not tried yet.

Is it only in being able to customize which consensus module to use?

Also, are there an active blockchains on any cryptocurrency exchanges that are using XuperChain  (or XuperCore) for the blockchain?

Thanks again and have a good day.

**Comment by urontlee** [comment]
Hello, you are welcome.
Xupercore is the core of XuperChain. When you compile and set up the node locally, you will reference xupercore on github.com, so you can successfully compile and set up the node even if you don't use it.
In the configuration of the genesis block, the consensus module can customize which one to use when the chain is not running. After the chain is already running, the consensus upgrade process of voting proposals needs to be used to replace different consensus.
No cryptocurrency exchange currently uses XuperChain (or XuperCore) as the active blockchain of the blockchain.

**Comment by lonnietc** [comment]
@urontlee Thanks so much for this clarification on Xuperchain as I think that it is really a great blockchain.

As I am building a new cryptocurrency to get started on an exchange, I would like to ask if you as the XuperChain developers think that it is about production ready to go into public action with the features that it currently has now?   

Do you think that it is stable enough and can scale to thousands of nodes?

The question that I am having now is if I should utilize XuperChain or some other core blockchain for the new cryptocurrency to be introduced early next year for the project that is being developed now.

Thanks again

**Comment by lonnietc** [comment]
Hi All,

I have been following the documentation from:

https://xuperchain.readthedocs.io/zh/latest/quickstart.html

and based upon the discussion above, think that I would like to be able to change the consensus algorithm to either one of these:

tdpos
xpos
xpoa

but am not sure which to really use here.

Do I specify the proper json file in the data/genesis directory during the "./xchain createChain" phase?

**Comment by lonnietc** [comment]
@urontlee can you please tell me how to have my configuration so that my XuperChain will use XPoS by default?

I am trying to figure out the steps to get a Multi-Node cluster up and running:

https://xuper.baidu.com/n/xuperdoc/advanced_usage/multi_nodes.html

But using either TDPoS or XPoS by default.

when I issue the command:

~/XuperChain/test/output$ ./bin/xchain-cli consensus status
{
  "version": "0",
  "consensus_name": "single",
  "start_height": "1",
  "validators_info": "{\"validators\":[\"TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY\"]}"
}

which say that "single" is running and I wanted to start one seed node and two regular nodes (3 nodes total) for testing.
