### ISSUE TITLE
编译子模块xvm时出现h文件找不到

### ISSUE THREAD

**Issue by kyugao** [xuperchain/xuperchain#1093]
**Brief of the issue**
![image](https://user-images.githubusercontent.com/1071977/141233634-f805f162-34f8-40af-9062-2fbfa0977a14.png)

**Your environment**
XuperChain 5.1
Mac OS
Go 14
gcc version 11.2

**Repo steps**
按文档git clone -> make

**Comment by chenfengjin** [comment]
看起来像是include path 设置的问题，确认下本地 是否覆盖了环境变量。
编译过程中用到的环境变量参考 
https://github.com/xuperchain/xvm/blob/main/compile/wabt/Makefile

**Comment by chenfengjin** [comment]
可以重点看一下 CPPFLAGS，CFLAGS, INC_DIRS，INC_FLAGS 这几个变量

**Comment by kyugao** [comment]
请教下，考不考虑直接发布对应各平台的二进行可执行文件

**Comment by godeamon** [comment]
目前只有 3.12 版本，5.1 还未发布二进制形式：https://xuper.baidu.com/n/xuperdoc/v3.12/advanced_usage/release.html

**Comment by kyugao** [comment]
成功。
