### ISSUE TITLE
使用utxo merge命令合并零碎UTXO失败

### ISSUE THREAD

**Issue by vantinfy** [xuperchain/xuperchain#1096]
**Brief of the issue**
三节点测试，使用utxo merge命令报错：not enough available utxo to merge

**Your environment**
XuperChain 5.1
OS Ubuntu
Go 1.15.9
gcc 8.4

**Repo steps**
make testnet后cd到node1目录下
```shell
./bin/xchain-cli utxo merge
```

**What actually happened**
SelectUTXOBySize方法最后会检查utxoInput中的NeedLock参数
![image](https://user-images.githubusercontent.com/49287896/141754536-581b713b-60cf-4156-bd75-d1e89d2a08fc.png)
![image](https://user-images.githubusercontent.com/49287896/141755463-b2bfe837-f1b1-4c25-9a77-48a62dfe41e6.png)
如果NeedLock为true会对公钥和签名进行校验
![image](https://user-images.githubusercontent.com/49287896/141755806-7fa8f888-0072-4a0a-a0bc-03d9f558197e.png)
但comm_trans.go的GenTxInputsWithMergeUTXO方法并没有传入公钥跟签名（图1）

**Expected behaviours**
测试将Need改为false时执行merge命令是可以生成交易信息的。

**Comment by godeamon** [comment]
收到，感谢，我们已经在跟进了。
