### ISSUE TITLE
建议可以设置在没有业务交易时,不要自动出块

### ISSUE THREAD

**Issue by springrain** [xuperchain/xuperchain#1098]
**Brief of your idea**
目前即便没有交易,xuperchain也会默认3秒出块,实际会增加无意义的数据块.建议可以设置在没有业务交易时,不要自动出块.

**What could be better if XuperChain using your idea**
不会产生无意义的块

**Comment by qizheng09** [comment]
好的，记下这个需求了~ 后续会跟进~
