### ISSUE TITLE
Building for Windows?

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1101]
Hello,

What is the build process for Windows?

Thanks

**Comment by chenfengjin** [comment]
XuperChain is designed for unix-like system. it has bean strictly tested on MacOS  and some Linux distribution(Centos/Ubuntu). it has never verified Windows system although some of our customers use Windows as develop environment. 
if you are using a windows system, [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) or virtual  machine like [VirtualBox](https://www.virtualbox.org/) may be a good choose

**Comment by lonnietc** [comment]
Thanks for the info on this.

This is not really critical to the goals that we have but was more of an interest since Golang allows for choosing the platforms to compile against.
