### ISSUE TITLE
Does XuperChain establish transaction fees?

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1102]
Hello,

I have been reading up on the XuperChain blockchain and am trying to determine if it incorporates TX transactions fees for sending and receiving tokens?

If so, then I would assume that there is a wallet address that is established when the boot node comes up for this purpose, but cannot find any information on it.

Of course, there are a couple of existing blockchains (i.e. NANO, Mana, etc.) that do not have GAS fees and are truly fee-less but I would like to know how XuperChain is configured in this area.

Any information would be helpful.
Thanks in advance

**Comment by urontlee** [comment]
Hello, what xuperchain provides is a tool-like technical service for building your own chain, so gas fees can be defined by yourself. If you don’t want your chain to incur gas fees during transactions, you can put it in the "xuper.json" file , Set the "nofee" parameter to "true".

**Comment by lonnietc** [comment]
Hello, Thanks for getting back to me on this.

So then, if I understand correctly then:

1. If I want gas fees then that can be specified in the "xuper.json". 

{
    "version": "1",
    "predistribution": [
        {
            "address": "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY",
            "quota": "100000000000000000000"
        }
    ],
    "maxblocksize": "128",
    "award": "1000000",
    "decimals": "8",
    "award_decay": {
        "height_gap": 31536000,
        "ratio": 1
    },
    "gas_price": {
        "cpu_rate": 1000,
        "mem_rate": 1000000,
        "disk_rate": 1,
        "xfee_rate": 1
    },
    "new_account_resource_amount": 1000,
    "genesis_consensus": {
        "name": "single",
        "config": {
            "miner": "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY",
            "period": "3000"
        }
    }
}

Then where are the fees sent?   

Are they sent to the address "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY"?

2. If no gas fees are desired then, would it be correct to change the "gas_Price" section to be:

    "gas_price": {
        "nofee": true
    },


Also, for the genesis address "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY" how is a new one generated as that seems to be static in the files?

**Comment by urontlee** [comment]
Our gas fee will be distributed to the miners, not just the address in the genesis block, this is related to the consensus mechanism, I recommend you to directly look at the relevant code, everything is subject to the code.

**Comment by lonnietc** [comment]
I'm sorry for all of the questions on XuperChain as I am just trying to get a feel for things and think that it has HUGE potential to be a great blockchain.

You actually confuse me now in that my understanding was that XuperChain as a "non-mineable" blockchain but now you mention that the miners will get the gas fees.

**Comment by lonnietc** [comment]
I am reading the documentation link that was sent to me in another post today:

https://xuper.baidu.com/n/xuperdoc/quickstart/quickstart.html

but basically want to set up a XuperChain blockchain with these properties:

1. Non-Mineable and no gas fees.
2. Either TDPOS, XPOA, or XPOS  (which ever is better)
3. New token name and new quantity.
4. New Genesis pre-distributed address

Any help and guidance would be greatly appreciated.

**Comment by urontlee** [comment]
I suggest you follow the documentation first, and then there are design principles in the "v5.1.0" document I recommend to you. I suggest reading the complete document before deciding how to customize your own chain. .

**Comment by lonnietc** [comment]
You are correct and that is exactly the approach that I am taking.

Mostly, I have just been posting questions that are raised in my mind while I am reading the documentation and testing the default setup in preparations for customizations later.
