### ISSUE TITLE
Question on Genesis (xuper.json)

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1103]
Hello,

I am working through the documentation to run XuperChain after compiling it and have a question regarding the "/data/genesis" files.

In particular, I see a static address "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY" in the designation of the Xuper token and am wondering how this is generated and how to generate a new one:

 (example xuper.json)
{
    "version": "1",
    "predistribution": [
        {
            "address": "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY",
            "quota": "100000000000000000000"
        }
    ],
    "maxblocksize": "128",
    "award": "1000000",
    "decimals": "8",
    "award_decay": {
        "height_gap": 31536000,
        "ratio": 1
    },
    "gas_price": {
        "cpu_rate": 1000,
        "mem_rate": 1000000,
        "disk_rate": 1,
        "xfee_rate": 1
    },
    "new_account_resource_amount": 1000,
    "genesis_consensus": {
        "name": "single",
        "config": {
            "miner": "TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY",
            "period": "3000"
        }
    }
}

**Comment by urontlee** [comment]
Hello, the default address in "xuper.json" is our built-in address, which is equivalent to the node address when you start the chain. This address can be generated through the account module of xchain-cli. You can create a normal account. In "data/keys/address", it is the address of the account.

**Comment by lonnietc** [comment]
Hi and Tanks so much for your responses as they are very helpful.

In your quickstart (https://xuperchain.readthedocs.io/zh/latest/quickstart.html)  

I think that your documentation needs to be changed since section "2.1.1. Create a chain" says:

./xchain-cli createChain

but the actual command is now:

./xchain createChain

Also, I will try to generate a new built-in address since this will be a new blockchain.

**Comment by urontlee** [comment]
Sorry, the document you read is biased. I recommend you to read this document corresponding to v5.1.0: https://xuper.baidu.com/n/xuperdoc/quickstart/quickstart.html#xuperchain

**Comment by lonnietc** [comment]
Thanks for the link and I will read up on it now, my friend.

**Comment by lonnietc** [comment]
Hello,

I am reading the new 5.1 Docs and am testing with a single node at first to just get started.

I see that you can transfer tokens from one account to another and as your Section "2.2.3 Transfer" describes, it is transferring:

--to czojZcZ6cHSiDVJ4jFoZMB1PjKnfUiuFQ  (Wallet Address)
--keys data/keys/ 

but

Can it transfer 

--to  (Wallet Address)
--from (Waller Address)

to do wallet to wallet transfers?

 See Below.

2.2.3. Transfer
The transfer operation needs to provide the private key directory of the source account, which is similar to the directory generated in "2.1.1 Create New Account". Note here that there is no need to provide any key of the target account, only the address is required.

# --keys 从此地址 转给 --to地址 --amount 金额
$ bin/xchain-cli transfer --to czojZcZ6cHSiDVJ4jFoZMB1PjKnfUiuFQ --amount 10 --keys data/keys/ -H 127.0.0.1:37101

24d53ea6e61ede8dc4fe65a04fd30da17c079a359e700738f8795dfddc55ffb4

**Comment by urontlee** [comment]
Can transfer from one account to another

**Comment by lonnietc** [comment]
Thanks again.

The more that I read up on things, but better I understand and get a feel for XuperChain.

Its a great blockchain and I like it more and more.
