### ISSUE TITLE
Specifying different consensus?

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1104]
Hi All,

I have been following the documentation from:

https://xuperchain.readthedocs.io/zh/latest/quickstart.html

and based upon the discussion above, think that I would like to be able to change the consensus algorithm to either one of these:

tdpos
xpos
xpoa

but am not sure which to really use here.

Do I specify the proper json file in the data/genesis directory during the "./xchain createChain" phase?

Also, to change consensus I am guessing that one of the "output/conf/ config files tells xchain which "data/genesis/{consensus}" files to use and the default is "xuper.json".

Given that one of the above 3 are probably better, then how do I configure xchain to use perhaps "tdpos.json", "xpos.son", or "xpoa.json" in the genesis directory instead?

**Comment by urontlee** [comment]
Hello, when the chain is not created, you can copy "xpoa.json", "xpos.json" and other content in the consensus file you want to replace into the xuper.json file. xuper.json is the startup configuration of the chain document.

**Comment by lonnietc** [comment]
Thanks my friend, as this is greatly helpful and exactly what I needed to know.

I will do this for the xpoa.json and copy it to xuper.json so that it will be used.
