### ISSUE TITLE
XuperChain Desktop and/or Mobile Token Wallet?

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1106]
Hello, 

Hope that you are doing well on this happy Friday.

I am looking to see if Xuper has any desktop and/or mobile token wallets available?

I have been able to locate an older "Xuper Wallet - Web"

https://github.com/xuperchain/xuper-wallet-web

but have not tested it yet and was also interested in seeing if there were other wallets available as well.
Thanks again

**Comment by uaanaa** [comment]
Hello, we don’t have any form of wallet application yet.  the one you see cannot be used. We will have.

**Comment by lonnietc** [comment]
Thanks and I will work on that part a little later once we have the basic cluster working.

Happy Holidays
