### ISSUE TITLE
Question on pre-distributed account

### ISSUE THREAD

**Issue by lonnietc** [xuperchain/xuperchain#1110]
Hello,

I have been working with the 3-node TESTNET to get a feel for things and bring up the nodes with no problem.

then:
# Check the Keys main account
$ bin/xchain-cli account balance TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY
100000000000038000000

# Create Bob and chack account
$ bin/xchain-cli account newkeys --output data/bob
$ bin/xchain-cli account balance eYKe14ok9XQ1jdCGjdmNJSWsMhS1R6cxr
0

# Transfer some to Bob
$ bin/xchain-cli transfer --to eYKe14ok9XQ1jdCGjdmNJSWsMhS1R6cxr --amount 100 --keys data/keys/ -H 127.0.0.1:37101
4e4e1ce92aa0a1a1496801695c1ab5bce89b6a99757194007187799fa5cc3fa2

# Check Bob account
$ bin/xchain-cli account balance eYKe14ok9XQ1jdCGjdmNJSWsMhS1R6cxr
100

# Check the Pre-Distributed account
$ bin/xchain-cli account balance TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY
100000000000124999900

# Transfer large amount to Bob
$ bin/xchain-cli transfer --to eYKe14ok9XQ1jdCGjdmNJSWsMhS1R6cxr --amount 100000000 --keys data/keys/ -H 127.0.0.1:37101
60b896b9adbea6314a1130e1f8e99f5553caa1f1a33601925e0d7e056bb5ffe4

# Check Bob account again
$ bin/xchain-cli account balance eYKe14ok9XQ1jdCGjdmNJSWsMhS1R6cxr
100000100

# Check the Pre-Distributed account
$ bin/xchain-cli account balance TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY
100000000000031999900

The question that I have is that the main "data/keys"  Pre-Distribution account  seems to increase little-by-little due to mining which is correct, but that when I TRANSFER tokens OUT of the main data/keys account then the main balance does not seem to decrease.

Is this correct?

I would expect for the "data/keys" account to decrease as tokens are transferred to Bob, and others.

Or, is the purpose of the "data/keys" initial account to maintain a cumulative sum total MAX tokens for the whole network?

Can you please clarify?

Thanks and Happy Holidays

**Comment by uaanaa** [comment]
The built-in token in data/keys is only pre-allocated to a certain address for test transfer use. This pre-allocated Token can be configured through the fields in xuper.json.

**Comment by lonnietc** [comment]
Hello, i have already tried to configure through the xuper.json file but it
creates 2 blockchains (xuper and Q) which is why i posted the issue

Thanks

**Comment by lonnietc** [comment]
Please try to rename xuper to something else to replicate the problem.

Or, name a new blockchain via the command line and see the problem.

**Comment by lonnietc** [comment]
Sorry, but I think that I answered the question here referring to my other post about changing the token and ledger name from xuper to something else.

https://github.com/xuperchain/xuperchain/issues/1109

When you create a new chain with:

$ ./bin/xchain -n=Q createChain
then
$ bash control.sh start

Then the data/blockchain directory 

/Q
/xuper

And thus 2 ledgers are built when there should only be 1 called "Q".

Can you please try to replicate this to see what the problem is?
Thanks and Happy New Year.

**Comment by lonnietc** [comment]
My main question here for this issue (#1110) is if when you transfer tokens from the pre-distribution account then should that total number decrease?

The default xuper pre-distribution address is " TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY " which was set in the config files but when you transfer tokens out of it then the total does not decrease for some reason and still shows the total that you began with plus any that were recently mined are also added.

My problem is that I would expect that the total tokens in that account should decrease when they are transferred to another address wallet.

**Comment by lonnietc** [comment]
Problem solved.

Thanks
