### ISSUE TITLE
在环境部署的第一步 make 时中断报错

### ISSUE THREAD

**Issue by ifishnet** [xuperchain/xuperchain#1111]
**Brief of the issue**
build xvm error:
make[1]: Entering directory '/home/xuperchain/.compile_cache/xvm/xvm/compile/wabt'
make[1]: *** 没有指明目标并且找不到 makefile。 停止。
make[1]: Leaving directory '/home/xuperchain/.compile_cache/xvm/xvm/compile/wabt'
complie xvm failed
Makefile:24: recipe for target 'xvm' failed
make: *** [xvm] Error 1

**Your environment**
XuperChain V5.1.0
GO version go1.15.6 linux/amd64
Oracle VM VirtualBox ，OS linux 4.15.0-30deepin-generic
CPU AMD 5950X 16-Core

**Repo steps**
我同样的配置创建了一个新的虚拟机 使用centos8 一切正常

**Expected behaviours**
 recipe for target 'xvm' failed 
 build 中断无法继续执行

**What actually happened**
在环境部署的第一步 make 时中断报错

**Additional information**
以上问题我暂时是使用以下方式解决的:
```
function buildxvm() {
    # clean dir
    ----
    ----

    # download pkg

    # unzip
	
     sleep 5  #加入等待时间(暂且解决)
	
   # make
	    
}
```

buildxvm 函数中的 #unzip 与 #make 之间 等待5秒中待文件全部复制完毕再向下执行

**Comment by uaanaa** [comment]
请提供一下完整的操作步骤和日志

**Comment by ifishnet** [comment]
https://gateway.pinata.cloud/ipfs/QmcQtG9ptVuboNc6wD3f4HbzENETTWC7p35Eib19Z8oVa9/20211227_154317.mp4

我录了一个操作视频

**Comment by uaanaa** [comment]
看了你的视频，你直接使用centos吧， OS linux 4.15.0-30deepin-generic 这个环境现阶段不建议使用。

**Comment by ifishnet** [comment]
我现在也在用centos , OS linux 4.15.0-30deepin-generic这个环境目前只发现 在make时报错 编译后运行都一切正常

**Comment by uaanaa** [comment]
嗯好的，谢谢你的支持和关注
