### ISSUE TITLE
部署 wasm 合约 出错 no enough money

### ISSUE THREAD

**Issue by fuyi501** [xuperchain/xuperchain#1122]
**Brief of the issue**
我按照 https://xuper.baidu.com/n/xuperdoc/advanced_usage/contract_management.html 这个文档里的操作进行，创建了 1111111111111111 合约账户，也进行了转账，有足够的余额，但是在进行合约部署时出错

```sh
output git:(v5.1.0) ✗ ./bin/xchain-cli wasm deploy --account XC1111111111111111@xuper  -a '{"creator":"XC1111111111111111@xuper"}' --cname counter counter.wasm --fee 355003
contract response: initialize succeed
The gas you cousume is: 155301
The fee you pay is: 355003
Select utxo error, details:rpc error: code = Unknown desc = Err:500-50001-unknown error+no enough money(UTXO) to start this transaction
```

<img width="821" alt="image" src="https://user-images.githubusercontent.com/20770905/153534389-b1826177-3cb7-4227-8f57-d8a879e5ccfe.png">
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/20770905/153534425-188b05bc-9b66-43ab-88af-5e19bdd152c5.png">

**Comment by MoonS11** [comment]
请问解决了吗
