### ISSUE TITLE
native contract 为什么没有生成docker容器呢

### ISSUE THREAD

**Issue by zhiguogg** [xuperchain/xuperchain#1140]
![image](https://user-images.githubusercontent.com/50401300/165458026-d6ddbaa2-b41f-4c62-a3dd-fc7f746fe549.png)

按照文档部署JAVA合约，怎么是个本地进程？怎么样才能运行在docker容器呢？

**Comment by uaanaa** [comment]
链是在docker 中运行的吗？

**Comment by zhiguogg** [comment]
@uaanaa 我这个链不是在docker运行的。链要是在docker中运行，那么部署native合约是在这个docker容器中起一个本地进程，还是这个native合约会重新起一个docker？

**Comment by uaanaa** [comment]
单合约放在docker 的话，看下这里的配置  output/conf/contract.yaml ， 需要有支持java运行的容器。centos 默认不支持java 程序运行，另外，不支持Mac

`# 管理native合约的配置
native:
  enable: true

  # docker相关配置
  docker:
    enable: false
    # 合约运行的镜像名字
    imageName: "docker.io/centos:7.5.1804"
    # cpu核数限制，可以为小数
    cpus: 1
    # 内存大小限制
    memory: "1G"`

**Comment by zhiguogg** [comment]
@uaanaa docker配置信息中 enable 需要为true吗？imageName是一个支持java运行的容器即可吗？

**Comment by uaanaa** [comment]
是的

**Comment by zhiguogg** [comment]
@uaanaa 谢谢！
