### ISSUE TITLE
执行bin/xchain-cli status -H 127.0.0.1:37101出现错误

### ISSUE THREAD

**Issue by mumingbai** [xuperchain/xuperchain#1141]
问题
执行bin/xchain-cli status -H 127.0.0.1:37101出现错误

您的环境
linux c 7.9
Go 1.14.2

操作步骤
![image](https://user-images.githubusercontent.com/33116005/167861099-a925d772-5f05-4d22-a93f-76f078e56ba0.png)

安装完成后前几部都没问题，云主机的防火墙也都关掉了服务器后台也开放了该端口
![image](https://user-images.githubusercontent.com/33116005/167860156-09d91c4f-0f7c-458e-8b51-38e5a2cf9a72.png)

具体问题

执行
`bin/xchain-cli status -H 127.0.0.1:37101`
报错

`rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:37101: connect: connection refused"`
各位大佬请问是什么原因啊提前非常感谢您的解答

**Comment by mumingbai** [comment]
> 是不是37101 端口被占用了呢？ 如果没有可以稍等几秒再查询状态，端口启动也需要时间

感谢刚启动了一下确实是可以了非常感谢

**Comment by kaventre** [comment]
我也是相同的错误，但是一直都没办法使用

**Comment by zhugelianglongming** [comment]
> 我也是相同的错误，但是一直都没办法使用

日志对于执行的记录信息提示了什么呢？

**Comment by godeamon** [comment]
> > 我也是相同的错误，但是一直都没办法使用
> 
> 日志对于执行的记录信息提示了什么呢？

看下日志中是否有错误信息，nohup.out 和 xchain.log

**Comment by kaventre** [comment]
您好，在昨天的测试中我无意的解决了这个问题，但很快当我重新测试后又出现了相同的问题，我怀疑是端口被占用了，但是在我查看端口情况后，似乎又是正常情况，日志文件比较大，您那边好像无法正常接收，如果需要可以添加微信或者QQ吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuperchain/xuperchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月30日(星期一) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuperchain/xuperchain] 执行bin/xchain-cli status -H 127.0.0.1:37101出现错误 (Issue #1141)





   
我也是相同的错误，但是一直都没办法使用
  
日志对于执行的记录信息提示了什么呢？
  
看下日志中是否有错误信息，nohup.out 和 xchain.log

**Comment by godeamon** [comment]
> 您好，在昨天的测试中我无意的解决了这个问题，但很快当我重新测试后又出现了相同的问题，我怀疑是端口被占用了，但是在我查看端口情况后，似乎又是正常情况，日志文件比较大，您那边好像无法正常接收，如果需要可以添加微信或者QQ吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuperchain/xuperchain" ***@***.***&gt;; 发送时间:&nbsp;2023年1月30日(星期一) 下午2:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xuperchain/xuperchain] 执行bin/xchain-cli status -H 127.0.0.1:37101出现错误 (Issue #1141) 我也是相同的错误，但是一直都没办法使用 日志对于执行的记录信息提示了什么呢？ 看下日志中是否有错误信息，nohup.out 和 xchain.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，这个 issue 已经 close 了，您再开一个新的 issue 描述您的问题吧，谢谢！

**Comment by kaventre** [comment]
您好，在昨天的测试中我无意的解决了这个问题，但很快当我重新测试后又出现了相同的问题，我怀疑是端口被占用了，但是在我查看端口情况后，似乎又是正常情况，日志文件比较大，您那边好像无法正常接收，如果需要可以添加微信或者QQ吗…发自我的手机-------- 原始邮件 --------发件人： Brian ***@***.***>日期： 2023年1月30日周一 下午2:14收件人： xuperchain/xuperchain ***@***.***>抄送： kaventre ***@***.***>, Comment ***@***.***>主    题： Re: [xuperchain/xuperchain] 执行bin/xchain-cli status -H 127.0.0.1:37101出现错误 (Issue #1141)



我也是相同的错误，但是一直都没办法使用



日志对于执行的记录信息提示了什么呢？
