### ISSUE TITLE
git拉取项目后make报错

### ISSUE THREAD

**Issue by LuckyYp** [xuperchain/xuperchain#1144]
错误信息：rm -rf /usr/local/xuperchain/output
bash /usr/local/xuperchain/auto/build_xvm.sh
start downloading xvm pkg...
/usr/local/xuperchain/auto/build_xvm.sh: line 23: unzip: command not found
mv: cannot stat ‘/usr/local/xuperchain/.compile_cache/xvm/xvm-main’: No such file or directory
make: *** /usr/local/xuperchain/.compile_cache/xvm/xvm/compile/wabt: No such file or directory.  Stop.
complie xvm failed
make: *** [xvm] Error 1

**Comment by uaanaa** [comment]
unzip: command not found  安装一下 unzip 这个命令

**Comment by LuckyYp** [comment]
感谢，已解决
