### ISSUE TITLE
根据账户地址查询交易记录

### ISSUE THREAD

**Issue by CyrusLiu158** [xuperchain/xuperchain#1147]
**Brief of your idea**
cli增加命令，可以查询某个账户下的交易记录
bin/xchain-cli account  txquery [address] -H 127.0.0.1:37101

**What could be better if XuperChain using your idea**
以太坊的区块链浏览器可以根据地址查询

**Additional information**
类似于这种：https://etherscan.io/address/0x5e201a38da7f5BC62bc8aebd2BB816a101676162

**Comment by uaanaa** [comment]
开源版本区块链浏览器：https://github.com/xuperchain/xuperscan

**Comment by CyrusLiu158** [comment]
> 开源版本区块链浏览器：https://github.com/xuperchain/xuperscan

这个版本只能根据三个条件：区块哈希/区块高度/交易哈希
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/3727646/169628014-68422706-d828-4cff-aa35-aa0b964e7022.png">
而以太坊支持5个条件，最关键的就是账户地址
<img width="949" alt="image" src="https://user-images.githubusercontent.com/3727646/169628053-c4266fec-886c-4059-95be-4e44d1e9a7ea.png">
比如，我想查某个账户/合约账户的全部交易记录，目前开源浏览器是不支持的

**Comment by uaanaa** [comment]
xuperscan 是支持地址查询的哈

**Comment by CyrusLiu158** [comment]
> https://github.com/xuperchain/xuperscan

请问是否有公开的验证链接，我在github拉的代码，是无法按照address搜索的。谢谢
另外这个地址，是账户地址、还是合约账户地址，或者是两者都支持么

**Comment by uaanaa** [comment]
https://xuper.baidu.com/n/explorer

**Comment by CyrusLiu158** [comment]
> https://xuper.baidu.com/n/explorer

好奇怪，用开源项目，是没有的😂
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/3727646/169940783-cc0fb06d-c370-457c-b4e7-22929a9d917b.png">
这个项目：https://github.com/xuperchain/xuperscan
难道是branch不对？

**Comment by uaanaa** [comment]
对的，是一样的，你那里地址产生交易之后， 输入地址查询会报错吗？

**Comment by CyrusLiu158** [comment]
> 对的，是一样的，你那里地址产生交易之后， 输入地址查询会报错吗？

根据地址查不到结果
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/3727646/169963697-dfd76abf-5edc-42bd-8f35-5d5199796b89.png">

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/3727646/169963634-0d85df77-5e8f-437e-8882-2881dd8ff26e.png">

只有根据交易id才能查到结果，根据地址不行
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/3727646/169963816-7265253c-0b38-42d9-bcf2-89c8fd583412.png">

**Comment by uaanaa** [comment]
好的，辛苦在 xuperscan 提个issues，我们后续在浏览器那边跟进，这个issues 如果没有别的问题可以关闭

**Comment by CyrusLiu158** [comment]
> 对的，是一样的，你那里地址产生交易之后， 输入地址查询会报错吗？

根据地址是查不到结果的，只能根据txid
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/3727646/169964357-0b7e0eea-d43f-4158-a506-ff2034fadfb8.png">
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/3727646/169964450-5f7e5d07-5bf6-472e-b306-7049c41dcf9c.png">
我看了下cli命令，貌似也只有根据txid查询
<img width="721" alt="image" src="https://user-images.githubusercontent.com/3727646/169964574-ee2d8a3a-9ce7-49b7-88af-6467c03fe263.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/3727646/169964672-274061a2-9c34-414b-8bc7-06c09222410c.png">

**Comment by CyrusLiu158** [comment]
> 

好的

**Comment by uaanaa** [comment]
是的，cli工具与sdk都只能通过交易id查询交易详情
