### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by ajiewhy** [xuperchain/xuperchain#1152]
**Brief of the issue**
![image](https://user-images.githubusercontent.com/17778736/172405162-14079e7b-3537-4ec7-a019-637e25e129da.png)

**Your environment**
macOS 12.3/
Go：go version go1.18.3 darwin/arm64

**Repo steps**
make

# golang.org/x/sys/unix
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
**../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200824131525-c12d262b63d8/unix/zsyscall_darwin_arm64.go:121:3: too many errors**
compile done!

**Comment by uaanaa** [comment]
go 版本建议使用1.15.x

**Comment by yyparty** [comment]
编译报错！！！
Environment variable XVM_BUILD_MAIN not set. 这个环境变量在哪里设置

**Comment by userInner** [comment]
export XVM_BUILD_MAIN=.
