### ISSUE TITLE
Ubuntu run control.sh with: "Syntax error: Bad for loop variable"

### ISSUE THREAD

**Issue by zhugelianglongming** [xuperchain/xuperchain#1171]
**Brief of the issue**
Run control.sh with error: `Syntax error: Bad for loop variable` 

**Your environment**
- XuperChain: v5.3.0
- OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1023-azure x86_64)
- Go: go1.18.1 linux/amd64
- Gcc: 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

**Repo steps**
1. Download Xuperchain v5.3.0
2. `make && make testnet`
3. `cd testnet/node*`
4. `sh control.sh start`

**Expected behaviours**
```
...
start finish.pid:<PID>
Done!
```

**What actually happened**
```
Syntax error: Bad for loop variable
```
![image](https://user-images.githubusercontent.com/4128595/203912649-70d31bd6-aafc-4fec-8634-8f69f4a3854a.png)
> Picture shows script run with `set -x`

**Additional information**
Fix problem by `bash control.sh start`

Problem cause and solution: [Syntax error: Bad for loop variable错误解决方法](https://blog.csdn.net/hu5566798/article/details/106665458)

**Comment by Jasonwu123** [comment]
Ubuntu下的sh命令是软连接到 /bin/dash，但是启动脚本里用的/bin/bash，所以你可以用bash control.sh start启动试试。

**Comment by zhugelianglongming** [comment]
> Ubuntu下的sh命令是软连接到 /bin/dash，但是启动脚本里用的/bin/bash，所以你可以用bash control.sh start启动试试。

对的，我也是这么解决的
