### ISSUE TITLE
PreExe contract response : rpc error: code = Unknown desc = Err:500-50501-contract invoke failed+unsupported native contract runtime c

### ISSUE THREAD

**Issue by chaunsin** [xuperchain/xuperchain#1190]
**Brief of the issue**
使用命令行部署golang合约出现错误以下错误

```shell
bin/xchain-cli native deploy --account XC2222222222222222@xuper -a '{"creator":"root"}' --cname test_go_1 mycc 
PreExe contract response : rpc error: code = Unknown desc = Err:500-50501-contract invoke failed+unsupported native contract runtime c, logid:1672396072_2275839011630058
```

**Your environment**

- Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) )  SMP Thu Nov 8 23:39:32 UTC 2018
- go version go1.15.14 linux/amd64
- chain version:v5.1
- xchain-cli version release-v5.1-f4b8c19 2022-11-09-11:21:49

**Additional information**
请问是什么问题？

**Comment by uaanaa** [comment]
# 部署golang native合约
$ xchain-cli native deploy --account XC1111111111111111@xuper --fee 15587517 --runtime go -a '{"creator":"XC1111111111111111@xuper"}'   --cname golangcounter counter

看下报错是不是 runtime 没指定？

**Comment by chaunsin** [comment]
> # 部署golang native合约
> $ xchain-cli native deploy --account XC1111111111111111@xuper --fee 15587517 --runtime go -a '{"creator":"XC1111111111111111@xuper"}' --cname golangcounter counter
> 
> 看下报错是不是 runtime 没指定？

嗯解决了
