### ISSUE TITLE
调用合约出错

### ISSUE THREAD

**Issue by chaunsin** [xuperchain/xuperchain#1211]
**Brief of the issue**

在使用golang sdk 调用合约时出现错误

<img width="240" alt="image" src="https://github.com/xuperchain/xuper-sdk-go/assets/33649884/69f01301-0f5f-4762-b977-95c22d66b3d9">

**Your environment**

XuperChain and OS/Go/gcc version etc.

**Reproduce steps**

Describe how to reproduce this issue.

**Expected behaviours**

调用正常

**What actually happened**

Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**

我想问一下什么情况下会出现此错误问题,另外我查了下这个错误码17 貌似对应得枚举值是：

<img width="1142" alt="image" src="https://github.com/xuperchain/xuperchain/assets/33649884/43cde941-3547-4bed-8aac-deb11813932a">

不知是否是这个？如果是我如何避免呢？

Additional helpful information, including but not limited to:
- Logs
- Screenshot
- Minimal, complete, and verifiable example codes

This also helps check that the issue is not with your own code.

**Comment by superlitian** [comment]
合约执行出错了吧，可以贴一下合约代码 调用流程 参数等信息
