### ISSUE TITLE
执行make

### ISSUE THREAD

**Issue by userInner** [xuperchain/xuperchain#1212]
# Ubuntu 版本18.04
# 机器芯片：鲲鹏920
# go版本：go version go1.15.15 linux/arm64
##  执行make命令，运行错误如下
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bls381/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fp
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:530:2: undefined: mulAssignElement
go build -o /xuperTools/xuperchain/xuperchain/output/bin/xchain-cli -ldflags "-X main.Version=heads/v5.1.0 -X main.BuildTime=2023-06-15-01:01:51 -X main.CommitID=e235881" /xuperTools/xuperchain/xuperchain/cmd/client/main.go
# github.com/consensys/gurvy/bn256/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bls381/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bls377/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fp
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:530:2: undefined: mulAssignElement
compile done!

**Comment by superlitian** [comment]
go 升级到 1.18.x 试下呢

**Comment by userInner** [comment]
好像是不支持这个处理器。
