### ISSUE TITLE
切换验证节点时不打包交易

### ISSUE THREAD

**Issue by Ma-Jiang** [xuperchain/xuperchain#1228]
根据官方文档部署了三个验证地址，但是只有一个矿工地址出区块能打包，其他两个地址只出块不打包交易(只有系统验证交易)

**Comment by godeamon** [comment]
你好，请问 【其他两个地址只出块不打包交易(只有系统验证交易)】这个现象具体什么样？或者说是如何发现的？另外官方文档中部署三个节点只有node1是矿工出块节点，不知道是不是这个问题。

**Comment by Ma-Jiang** [comment]
三个矿工节点地址是系统生成的，我们也按照文档配置了验证地址。这三个地址只有主节点打包交易也就是node1节点，如何发现的：我们用脚本跑调用合约方法上链，有时成功有时候报错。我们就用递归去链上查询是否上链成功，成功了再调合约上链。根据我们的排查，发现一个规律：我们三个节点端口分别是37102、37103、37104；  要是通过37102节点上链  37104节点地址验证的就很快 37102节点地址就只出块不打包交易和上链，如果用37104节点上链  37102节点地址就验证和上链很快 37104就不打包交易只是出空块   所有的交易就会集中到下个节点验证时 第一个块全部打包

**Comment by Ma-Jiang** [comment]
> 你好，请问【其他两个地址只出块不预留交易（只有系统验证交易）】这个具体是什么样的？或者说是现象如何发现的？另外官方文档中部署三个节点只有node1是矿工出块节点，不知道是不是这个问题。

三个矿工节点地址是系统生成的，我们也按照文档配置了验证地址。这三个地址只有主节点备用交易节点1节点，如何发现的：我们用脚本跑签名成功方法上链，有时有报错。我们就用递归去链上查询是否上链成功，成功的时候再调合约上链。根据我们的排查，发现一个规律：我们三个节点端口分别是37102、37103、37104；可惜通过37102节点上链 37104 节点地址验证的就很快 37102 节点地址就只出块不预留交易和上链，如果用 37104 节点上链 37102 节点地址就验证和上链很快 37104的交易就会集中到下个节点验证时第一个块全部资源

**Comment by godeamon** [comment]
如果发送交易的脚本速度很快，并且使用一个地址发送交易，由于 utxo 模型，很多交易是可能失败的，可以看下日志，查找下没有上链的交易哈希相关日志。

**Comment by Ma-Jiang** [comment]
![微信图片_20240517154640](https://github.com/xuperchain/xuperchain/assets/39143930/cb0cd9a7-1590-44c5-8c77-a96f23e8b9cd)
![微信图片_20240517154701](https://github.com/xuperchain/xuperchain/assets/39143930/db17c415-9ca2-4141-90c9-15d1c063529e)
上面的图片是三个节点   在切换验证的时候就会出现问题

现在我们只用了一个节点上链很快不会存在问题


> 如果发送交易的脚本速度很快，并且使用一个地址发送交易，由于 utxo 模型，很多交易可能会失败的，可以查看下日志，查找下没有上链的交易中断相关日志。

**Comment by godeamon** [comment]
我理解你们是把同一个地址的交易发送给了不同的节点，然后发现其中一些交易发送给非矿工节点时会发生不上链的情况，我理解的没错吧？如果是的话，这个情况是正常的，因为utxo模型，同一个地址在向不同节点发送交易时会导致utxo验证失败的。

**Comment by Ma-Jiang** [comment]
> 我理解你们是把同一个地址的交易发送给了不同的节点，然后发现其中一些交易发送给非矿工节点时会发生不上链的情况，我理解的没错吧？如果是的话，这个情况是正常的，因为utxo模型，同一个地址在向不同节点发送交易时会导致utxo验证失败的。

好的，谢谢解答。那这样只能用一个节点了

**Comment by godeamon** [comment]
同一个地址的交易，尽量向同一个地址发送，或者保证前一个交易上链成功后再发送下一笔，可以参考 BTC 的 utxo。

**Comment by Ma-Jiang** [comment]
> 同一个地址的交易，尽量向同一个地址发送，或者保证前一个交易上链成功后再发送下一笔，可以参考 BTC 的 utxo。

交易是完成了的，假如部署三个节点 每个节点验证10个块 那就是有20个块不会打包交易，剩下10个块前1个块会把前面所有交易都打包，后面9个块分别能打包30-40笔交易。并不是每个块都会打包交易只有一个节点打包交易，其他两个节点只是出空块

**Comment by godeamon** [comment]
交易本身也会 P2P 广播的，我理解你遇到的主要问题在于使用同一个地址快速发了很多交易，p2p广播交易导致一些交易后期验证失败。在一个地址快速发送交易时，最好是像同一个节点发送，这样即使其他节点验证失败，此节点后续也会打包这个用户的交易。另外可以尝试多账户并发交易。

**Comment by Ma-Jiang** [comment]
> 交易本身也会 P2P 广播的，我理解你遇到的主要问题在于使用同一个地址快速发了很多交易，p2p广播交易导致一些交易后期验证失败。在一个地址快速发送交易时，最好是像同一个节点发送，这样即使其他节点验证失败，此节点后续也会打包这个用户的交易。另外可以尝试多账户并发交易。

好的，谢谢解答
