### ISSUE TITLE
Unable to generate transaction of contract deployment

### ISSUE THREAD

**Issue by jiahaoc1993** [xuperchain/xuperchain#281]
**Brief of the issue**
Following to this [tutorial](https://github.com/xuperchain/xuperunion/wiki/%E8%B6%85%E7%BA%A7%E9%93%BE%E6%B5%8B%E8%AF%95%E7%BD%91%E7%BB%9C%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97) to deploy my first contract, everything is good until 4.3( contract deployment). I successfully created an account but failed to generate the transaction of contract deployment.

The output of `./xchain-cli wasm deploy --account XC8888888888666666@xuper --cname copy -H 14.215.179.74:37101 -m -A data/acl/addrs --arg '{"creator":"xchain234"}' --out
put contractRawTx.out --fee 144200 counter
` is as follows:
```
contract response: contract has not been banned
contract response: access permission succeed
contract response: initialize succeed
The gas you cousume is: 144184
The fee you pay is: 144200
Select utxo error, details:NOT_ENOUGH_UTXO_ERROR

```

**Your environment**
XuperUnion v3.2 branch and using the docker environment.

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Have an contractRawTx.out transaction as output

**What actually happened**
No output is created

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by qizheng09** [comment]
Have you ever transferred  sufficient resources to the contract account `XC8888888888666666@xuper` as [4.2](https://github.com/xuperchain/xuperunion/wiki/%E8%B6%85%E7%BA%A7%E9%93%BE%E6%B5%8B%E8%AF%95%E7%BD%91%E7%BB%9C%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#42-%E5%90%88%E7%BA%A6%E8%B4%A6%E6%88%B7%E5%85%85%E5%85%A5%E6%B5%8B%E8%AF%95%E8%B5%84%E6%BA%90) referenced？

**Comment by LordGoodman** [comment]
yes, I did. I transfered about 1000000 resource to XC8888888888666666@xuper

**Comment by yucaowang** [comment]
Hi @LordGoodman , is this issue resolved?
I checked the balance of "XC8888888888666666@xuper" on test environment and the result is 0.
I think it's something wrong when you transfer resources to the contract account.

**Comment by machen382847508** [comment]
I have a similar problem about contract deployment.  I successfully created an account but failed to generate the transaction of contract deployment.

./xchain-cli wasm deploy --account XC1111111111111111@xuper --cname newcounter --arg '{"creator": "counterwasm"}' -m --multiAddrs data/acl/addrs ./releate_file/counter

but having no output until the linux is break

**Comment by fxsjy** [comment]
@machen382847508 , you could start xchain like this: ./xchain --vm=ixvm. The default wasm vm will compile wasm to native code and use more than 4GB RAM. So, if your ram is small, please start xchain with wasm as `ixvm` mode, which will not compile wasm.

**Comment by machen382847508** [comment]
@fxsjy thanks for your help but when i start deploying counter,which from constractsdk,  it show me "desc= _initialize not found"

**Comment by fxsjy** [comment]
@machen382847508 , try add this into deploy command options : --runtime="go"

**Comment by yucaowang** [comment]
Close due to no response for a long time. Please reopen if this issue still happen.
