### ISSUE TITLE
Block should firstly save in temporary ledger not realy ledger.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperchain#289]
**Brief of your idea**
Now the block will be confirm in the ledger directly.
And then, utxovm will verify tx. If dotx function failed to ImmediateVerifyTx.
The node will walk error and utxototal is not going up.

**What could be better if XuperChain using your idea**

Block should firstly save in temporary ledger not realy ledger.
The block which pass ImmediateVerifyTx can be confirmed on the leadger.
This way can guarantee that the ledger of slave and master are the same,and the node which can sycblock successfuly  will not walk error.

**Are there any side effects?**
Describe what might be worse.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue.

**Comment by ToWorld** [comment]
closing this.
