### ISSUE TITLE
You need add fee problem

### ISSUE THREAD

**Issue by jiebanghan** [xuperchain/xuperchain#328]
hi 

when I run the commands below,
# 创建合约账户
## 通用方式
./xchain-cli account new --desc account.des
其中，account.des内容如下
{
    "module_name": "xkernel",
    "method_name": "NewAccount",
    "args" : {
        "account_name": "1111111111111111",  //说明：16位数字组成的字符串
        "acl": "{\"pm\": {\"rule\": 1,\"acceptValue\": 0.6},\"aksWeight\": {\"AK1\": 0.3,\"AK2\": 0.3}}"
    }
}
## 简易方式
./xchain-cli account new --account 1111111111111111  // 说明：16位数字组成的字符串

it show:
```
[Fri Aug 23 16:34:49]#./xchain-cli account new --desc account.des
contract response: {"pm": {"rule": 1,"acceptValue": 0.6},"aksWeight": {"AK1": 0.3,"AK2": 0.3}}
The gas you cousume is: 1000
You need add fee
[Fri Aug 23 16:35:38]#./xchain-cli account balance --keys data/accounts/bob -H 127.0.0.1:37101
0

```
but how to solve it ?thank you .

**Comment by MichelleZ** [comment]
./xchain-cli account new --desc account.des --fee 1000

**Comment by jiebanghan** [comment]
thank you ,but how and where to see all the command arguments and its meaning? For example I can't find the introduction of  the argument --fee  .

**Comment by jiebanghan** [comment]
I mean is there a document concerning the arguments?

**Comment by MichelleZ** [comment]
Enter this command：./xchain-cli account new -h, try it

**Comment by jiebanghan** [comment]
thank you . However, you mean I can only see the argments function with your method ? and  is there a document concerning the arguments?

**Comment by jiebanghan** [comment]
the fee I created the contract account is 1000, my question is : who pay the 1000 fee? who get the 1000 fee? thank you .

**Comment by jiebanghan** [comment]
the fee I created the contract account is 1000, my question is : who pay the 1000 fee? who get the 1000 fee? thank you .

**Comment by MichelleZ** [comment]
Do you know the mechanism of Bitcoin? It is similar to the concept of transaction fee.

**Comment by ToWorld** [comment]
closing this.
