### ISSUE TITLE
Nodes do not ignore transactions that are broadcasted twice.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperchain#396]
**Brief of the issue**
The transaction was executed locally and not overlooked when it was received again.

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
When the nodes received the transaction again, it will report wrong, as follows:
ImmediateVerifyTx: verifyRWSetPermission failed" module=xchain error="prepareEnv fail, k       ey:builtin_types^Agettx, inputs version is not valid: 260083db8fa64b126656896ea00fc334f734c7d0afabc0befc86ad93093f8ca5_0 != fb5e9       dfd9c785936fce1742a12f0a622be64aaa021e29435c23e80032b695dcc_0"

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
The issue has been addressed and closing this.
