### ISSUE TITLE
After cutting the ledger, stream not valid.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperchain#476]
**Brief of the issue**
Describe here

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
step1.
I cut the ledger with the blockid.and then restart the node.
step2
I found the height of ledger is right,but it not increase.
step3
I check the log,there is something wrong.
![image](https://user-images.githubusercontent.com/51076943/68367349-848cb400-0170-11ea-8089-888c7d188b34.png)

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
The issue has been addressed. Closing this.
