### ISSUE TITLE
pruning ledger failed: block not exist in this chain

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperchain#492]
**Brief of the issue**
Describe here

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
step1
After pruning ledger, the ledger height is not changed,but utxo height is changed;
step2
the log is :
pruning ledger failed: block not exist in this chain
**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
closing this.
