### ISSUE TITLE
function validateUpdateNewAccountResourceAmount  should return continue.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperchain#523]
**Brief of the issue**
![image](https://user-images.githubusercontent.com/51076943/69007137-e3260f00-0974-11ea-8aa2-8e715c3334e6.png)

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
The issue has been addressed and closing this.
