### ISSUE TITLE
Support import account

### ISSUE THREAD

**Issue by jolestar** [xuperchain/xuperchain#657]
**Brief of your idea**
Describe here

Account command should support import account with private key or mnemonic.

**What could be better if XuperChain using your idea**
Describe the benefits of your idea

User can import xchain public network account to local cli more easy.

**Are there any side effects?**
Describe what might be worse.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue.

**Comment by qizheng09** [comment]
Thank's for your advice, this will  support  through https://github.com/xuperchain/xuperchain/issues/697. This issue be closed here.
