### ISSUE TITLE
Restore private key with mnemonic

### ISSUE THREAD

**Issue by fxsjy** [xuperchain/xuperchain#697]
**Brief of your idea**
Users can use xchain-cli to restore private key with mnemonic

**What could be better if XuperChain using your idea**
more convenient

**Are there any side effects?**
no

**Additional information**
e.g. ./xchain-cli account restore

**Opened Issue**
https://github.com/xuperchain/xuperchain/issues/657

**Comment by gaojunjie03** [comment]
[https://github.com/xuperchain/XIP/pull/7](url)

**Comment by gaojunjie03** [comment]
[https://github.com/xuperchain/XIP/pull/7/files](url)
