### ISSUE TITLE
cross chain query bug ? 

### ISSUE THREAD

**Issue by gaojunjie03** [xuperchain/xuperchain#797]
When cross chain query is initiated in the contract, an error is reported: syscall method not found

Then I read the source code and found that the methodCrossContractCall value of contract_context.go is "CrossContractCall", while the corresponding cross chain method of syscall_service.go is "CrossContractQuery". Then I modified the methodCrossContractCall value to CrossContractQuery, so that I can successfully enter syscall_service.go

but another error msg :"ResolveChain error, err:get contract desc for 'crossQueryNaming' error:Key not found ctx id:10"

**Comment by qizheng09** [comment]
Have you deployed the `crossQueryNaming`  contract?

**Comment by gaojunjie03** [comment]
> Have you deployed the `crossQueryNaming` contract?

that is not my contract.
