### ISSUE TITLE
Can not locate the callee function of call_indirect

### ISSUE THREAD

**Issue by B-doublemint** [xuperchain/xuperchain#814]
Does table section change at runtime? I can't find the callee function of call_indirect instruction in table when I compile the luck_draw.cc to wasm file. If the table section can change at runtime, how to avoid?

**Comment by icexin** [comment]
The table is set during initialization and will not be changed at runtime. What do you mean by `I can't find the callee function of call_indirect instruction`?

**Comment by B-doublemint** [comment]
For example, in the wat file of luck_draw contract, I find a call_indirect instruction with immediate value "(type $t8) $T0", but I can't find a function with function type t8 in table section.

**Comment by icexin** [comment]
The table is initialized with the elem instruction, which has a function of type 8. btw, I use `wasm2wat` of wabt to convert wasm to wat format.

**Comment by B-doublemint** [comment]
Thank you, sir, could you please show me your luck_drraw.wat file? I did not find it.
