### ISSUE TITLE
创建合约账户

### ISSUE THREAD

**Issue by Tinrry** [xuperchain/xuperchain#913]
**Brief of the issue**
Describe here

**Your environment**
XuperChain and OS/Go/gcc version etc.
ubuntu 20.04

**Repo steps**
Describe how to reproduce this issue.

# 创建合约账户
## 通用方式
./xchain-cli account new --desc account.des
其中，account.des内容如下
{
    "module_name": "xkernel",
    "method_name": "NewAccount",
    "args" : {
        "account_name": "1111111111111111",  //说明：16位数字组成的字符串
        "acl": "{\"pm\": {\"rule\": 1,\"acceptValue\": 0.6},\"aksWeight\": {\"AK1\": 0.3,\"AK2\": 0.3}}"
    }
}
## 简易方式
./xchain-cli account new --account 1111111111111111  // 说明：16位数字组成的字符串

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
![image](https://user-images.githubusercontent.com/16282255/92878922-2212dd00-f43f-11ea-912c-95bc35d4c35a.png)

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.
What it mean? how can i fix it?

**Comment by chenfengjin** [comment]
you can add --fee 1000  to you command 
complete command is `  ./xchain-cli account new --account 1111111111111111 --fee 1000`
