### ISSUE TITLE
The timestamp of the transaction can not be trusted.

### ISSUE THREAD

**Issue by fxsjy** [xuperchain/xuperchain#92]
**Brief of the issue**
The timestamp of the transaction can not be trusted. And, it is set by client, but the xchain node does not verify it. Therefore, it can be fake.

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Comment by dengyi9** [comment]
Make xchain nodes to verify the timestamp might solve this problem. At Hyperledger Fabric, nodes will verify the transaction timestamp. It means transactions should be committed within a short time after it happened, like 5 minutes.

**Comment by ToWorld** [comment]
closing this.
