### ISSUE TITLE
TDPoS网络多节点部署问题

### ISSUE THREAD

**Issue by Fourth-fresh-man** [xuperchain/xuperchain#949]
**Brief of the issue**
按照文档配置完后，三台节点机器高度都为0
**Your environment**
XuperChain：latest version 
OS：centos8.2
Go：latest version
gcc：latest version
**Repo steps**
1、准备三台不同的虚拟机，分别名为n1，n2，n3，他们之间ssh免密且防火墙关闭，并且能够互通及上网
2、接下来操作都在root用户下进行，在n1机器上git clone xchain的源码，进入目录，进行make，将output文件内容复制到node文件夹内，删除掉node文件夹中keys和netkeys，分发给n2，n3
3、然后在n1，n2，n3上重新生成key和netkeys。查看n1，n2，n3的address，并记录到node_url文件
4、修改n1机器的xuper.json文件，分别是unix时间戳，矿工数量，参与轮选的矿工地址，也就是上面node_url文件内容，删除init_net_url部分
5、分发n1机器的xuper.json文件
6、n1机器进行建链操作，然后启动，查看n1的netURL，将其中127.0.0.1地址改为本机IP地址，并记录下来。
7、在n2，n3机器上分别修改xchain.yml文件，将它的bootnode节点改为上一步记录n1的netURL
8、在n2，n3机器上建链并启动
9、至此，所有我能收集到的资料均已查看完毕～，虽然区块高度一致，n1节点状态里，也有n2，n3机器IP地址，但是区块高度都为0，而根据成功案例的显示，一般是非0整数。

**Expected behaviours**
我本以为会成功显示区块高度一致，并且是非零整数～
**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
如果可以的话，我用docker来组建TDPoS网络会不会更容易一点～，当然前提是支持docker组建

**Comment by chunqizhi** [comment]
兄弟，我在本地三台 centos 虚拟机，没有问题啊

**Comment by Fourth-fresh-man** [comment]
> 兄弟，我在本地三台 centos 虚拟机，没有问题啊

请问你的区块高度是多少呢～

**Comment by chunqizhi** [comment]
> > 兄弟，我在本地三台 centos 虚拟机，没有问题啊
> 
> 请问你的区块高度是多少呢～

可以参考一下这个多节点部署脚本：[https://github.com/chunqizhi/xuperchain/blob/zcq-3.9/zcqadd.sh](url)

**Comment by Fourth-fresh-man** [comment]
> > > 兄弟，我在本地三台 centos 虚拟机，没有问题啊
> > 
> > 
> > 请问你的区块高度是多少呢～
> 
> 可以参考一下这个多节点部署脚本：[https://github.com/chunqizhi/xuperchain/blob/zcq-3.9/zcqadd.sh](url)

好的，谢谢指点，目前是自动恢复好了～在多机器多节点上可能需要一点时间同步才可以～
